tasks:
  - init: ./gradlew bootJar
    command: java -jar build/libs/springboot-hello-rest-0.0.1-SNAPSHOT.jar

# exposed ports
ports:
  - port: 8080
    onOpen: open-preview


vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot